### ISSUE TITLE
Merge the PRs :D

### ISSUE THREAD

**Issue by rohankalbag** [harpoonix/Gr-affable#47]
You guys do realise that PRs must be merged for them to be considered as successful contributions 😄

**Comment by harpoonix** [comment]
Thanks for the contributions, hopefully you learnt and enjoyed along the way! Do check out this [backtracking problem](https://github.com/harpoonix/Gr-affable/tree/main/Diwali), see if you like [encryption](https://github.com/harpoonix/Gr-affable/tree/main/Communication) or read [this](https://github.com/harpoonix/Gr-affable/blob/main/Closest-Points/closest_pair.pdf) fantastic paper on the classic divide and conquer problem!
